apiVersion: batch/v1
kind: Job
metadata:
  name: go-app-job-one-shot-task
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: go-app-job
          image: gcr.io/${PROJECT_ID}/go-app-job
      restartPolicy: Never