apiVersion: apps/v1
kind: Deployment
metadata:
  name: t04-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s-app
  template:
    metadata:
      labels:
        app: s-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.15-alpine
          ports:
            - containerPort: 80
