apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: t05-daemon
spec:
  selector:
    matchLabels:
      app: s-app
  template:
    metadata:
      labels:
        app: s-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.15-alpine