apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: t06-stateful
spec:
  serviceName: s-stateful
  replicas: 3
  selector:
    matchLabels:
      app: s-app
  template:
    metadata:
      labels:
        app: s-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.15
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1G
