apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-simple
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.12
          ports:
            - containerPort: 80
