apiVersion: batch/v1
kind: Job
metadata:
  name: golanghello
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: hello-container
          image: sky0621dhub/golanghello
      restartPolicy: Never