apiVersion: v1
kind: Service
metadata:
  name: sample-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: "TCP"
      name: "http-port"
  selector:
    app: app01